Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider "libvirt" do |vb|
    vb.default_prefix = ""
    vb.memory = "1024"
    vb.cpus = 1
  end

  (1..4).each do |i|
    config.vm.define "vm-#{i}" do |node|
    end
  end
end
